import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionLayout from "./components/layout/sessionLayout";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  console.log("rootSession:", session);

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionLayout session={session}>{children}</SessionLayout>
      </body>
    </html>
  );
}
